[package]
name = "rusted-red"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
serde = {version = "1.0.228", features=["derive"]}
serde_json = "1.0.145"
rusqlite = { version = "0.37.0", features = ["bundled"] }
